CREATE TABLE A(i INT, j INT, val INT);

INSERT INTO "A" VALUES (0,0,7);
INSERT INTO "A" VALUES (0,1,5);
INSERT INTO "A" VALUES (0,2,8);
INSERT INTO "A" VALUES (1,0,10);
INSERT INTO "A" VALUES (1,1,7);
INSERT INTO "A" VALUES (1,2,7);
INSERT INTO "A" VALUES (2,0,2);
INSERT INTO "A" VALUES (2,1,0);
INSERT INTO "A" VALUES (2,2,5);

CREATE TABLE B(i INT, j INT, val INT);

INSERT INTO "B" VALUES (0,0,9);
INSERT INTO "B" VALUES (0,1,6);
INSERT INTO "B" VALUES (0,2,10);
INSERT INTO "B" VALUES (1,0,7);
INSERT INTO "B" VALUES (1,1,6);
INSERT INTO "B" VALUES (1,2,9);
INSERT INTO "B" VALUES (2,0,1);
INSERT INTO "B" VALUES (2,1,1);
INSERT INTO "B" VALUES (2,2,7);
