CREATE TABLE streets(id INT, direction CHAR(1), A VARCHAR(255), B VARCHAR(255), d INT, PRIMARY KEY (id, direction));

INSERT INTO streets VALUES (0,'F','AUEB','DooHickey Collective',7);
INSERT INTO streets VALUES (0,'R','DooHickey Collective','AUEB',7);
INSERT INTO streets VALUES (1,'F','DooHickey Collective','Gizmo Corp',2);
INSERT INTO streets VALUES (1,'R','Gizmo Corp','DooHickey Collective',2);
INSERT INTO streets VALUES (2,'F','AUEB','Gadget Corp',6);
INSERT INTO streets VALUES (2,'R','Gadget Corp','AUEB',6);
INSERT INTO streets VALUES (3,'F','Gadget Corp','DooHickey Corp',3);
INSERT INTO streets VALUES (3,'R','DooHickey Corp','Gadget Corp',3);
INSERT INTO streets VALUES (4,'F','Gizmo Corp','GadgetWorks',8);
INSERT INTO streets VALUES (4,'R','GadgetWorks','Gizmo Corp',8);
INSERT INTO streets VALUES (5,'F','AUEB','Gadget Collective',9);
INSERT INTO streets VALUES (5,'R','Gadget Collective','AUEB',9);
INSERT INTO streets VALUES (6,'F','Gizmo Corp','Widget Industries',1);
INSERT INTO streets VALUES (6,'R','Widget Industries','Gizmo Corp',1);
INSERT INTO streets VALUES (7,'F','Gadget Corp','Gadget Industries',9);
INSERT INTO streets VALUES (7,'R','Gadget Industries','Gadget Corp',9);
INSERT INTO streets VALUES (8,'F','DooHickey Corp','DooHickeyWorks',3);
INSERT INTO streets VALUES (8,'R','DooHickeyWorks','DooHickey Corp',3);
INSERT INTO streets VALUES (9,'F','Gadget Industries','Widget Corp',5);
INSERT INTO streets VALUES (9,'R','Widget Corp','Gadget Industries',5);
INSERT INTO streets VALUES (10,'F','DooHickey Corp','ThingCo',6);
INSERT INTO streets VALUES (10,'R','ThingCo','DooHickey Corp',6);
INSERT INTO streets VALUES (11,'F','Gadget Collective','GizmoWorks',3);
INSERT INTO streets VALUES (11,'R','GizmoWorks','Gadget Collective',3);
INSERT INTO streets VALUES (12,'F','Widget Industries','Gizmo Industries',1);
INSERT INTO streets VALUES (12,'R','Gizmo Industries','Widget Industries',1);
INSERT INTO streets VALUES (13,'F','DooHickeyWorks','Thing Industries',1);
INSERT INTO streets VALUES (13,'R','Thing Industries','DooHickeyWorks',1);
INSERT INTO streets VALUES (14,'F','Thing Industries','Widget Collective',2);
INSERT INTO streets VALUES (14,'R','Widget Collective','Thing Industries',2);
INSERT INTO streets VALUES (15,'F','Thing Industries','Gizmo Collective',3);
INSERT INTO streets VALUES (15,'R','Gizmo Collective','Thing Industries',3);
INSERT INTO streets VALUES (16,'F','Widget Collective','DooHickeyCo',2);
INSERT INTO streets VALUES (16,'R','DooHickeyCo','Widget Collective',2);
INSERT INTO streets VALUES (17,'F','DooHickeyCo','Thing Collective',9);
INSERT INTO streets VALUES (17,'R','Thing Collective','DooHickeyCo',9);
INSERT INTO streets VALUES (18,'F','DooHickeyCo','Thing Corp',6);
INSERT INTO streets VALUES (18,'R','Thing Corp','DooHickeyCo',6);
INSERT INTO streets VALUES (19,'F','Widget Collective','WidgetWorks',1);
INSERT INTO streets VALUES (19,'R','WidgetWorks','Widget Collective',1);
INSERT INTO streets VALUES (20,'F','Widget Collective','GadgetCo',7);
INSERT INTO streets VALUES (20,'R','GadgetCo','Widget Collective',7);
INSERT INTO streets VALUES (21,'F','Thing Corp','GizmoCo',4);
INSERT INTO streets VALUES (21,'R','GizmoCo','Thing Corp',4);
INSERT INTO streets VALUES (22,'F','Thing Corp','DooHickey Industries',3);
INSERT INTO streets VALUES (22,'R','DooHickey Industries','Thing Corp',3);
INSERT INTO streets VALUES (23,'F','DooHickey Industries','WidgetCo',1);
INSERT INTO streets VALUES (23,'R','WidgetCo','DooHickey Industries',1);
INSERT INTO streets VALUES (24,'F','GizmoCo','ThingWorks',5);
INSERT INTO streets VALUES (24,'R','ThingWorks','GizmoCo',5);
INSERT INTO streets VALUES (25,'F','GadgetCo','Thing Industries',9);
INSERT INTO streets VALUES (25,'R','Thing Industries','GadgetCo',9);